Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'dt_files'
  Enabled: true

Layout/AlignHash:
  Exclude:
    - 'models.rb'
  EnforcedColonStyle: table

Layout/IndentHeredoc:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - 'dtag'
  Enabled: true

Style/FormatString:
  Exclude:
    - 'dtag'
  Enabled: true

Style/Documentation:
  Enabled: false
