#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'models'

# ds = DB[:images].where(film_id: :$i, filename: :$f)

FilmRoll.select(:id, :folder).order(:folder).all do |r|
  dir = r.folder
  unless Dir.exist?(dir)
    warn "no dir:#{dir}"
    next
  end
  Dir.entries(dir).each do |file|
    next unless File.file?("#{dir}/#{file}")
    next if file.match?(/\.(xmp|pto|pp3|xcf|orig|txt)$/i)

    if Image.where(film_id: r.id, filename: file).count.zero?
      puts "#{dir}/#{file}"
    end

    # if ds.call(:select, i: r.id, f: file).count.zero?
    #  puts "#{dir}/#{file}"
    # end
  end
end
