#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'oj'
require 'active_support/core_ext/string'
require 'active_support/core_ext/hash'
require_relative 'models'

# All in one restore class
class Restore
  ImageSt = Struct.new :file, :ver, :meta, :roll_id, :roll_name

  Op = Struct.new :dry, :v, :vv, :force, :add_tag, :del_tag,
                  :no_geo, :r_geo,
                  :no_meta, :del_meta

  def initialize
    @ignore_tags = []
    optparse
  end

  def optparse
    @o = Op.new
    OptionParser.new do |opts|
      opts.on('-n',     'dry run')  { @o.dry       = true }
      opts.on('-v',     'verbose')  { @o.v         = true }
      opts.on('--vv',   'very -v')  { @o.vv        = true }
      opts.on('-f',     'force')    { @o.force     = true }
      opts.on('--at',   'add tags') { @o.add_tag   = true }
      opts.on('--dt',   'del tags') { @o.del_tag   = true }
      opts.on('--rg N', 'round ll') { |n| @o.r_geo = Integer(n) }
      opts.on('--ng',   'no geo')   { @o.no_geo    = true }
      opts.on('--nm',   'no meta')  { @o.no_meta   = true }
      opts.on('--dm',   'del meta') { @o.del_meta  = true }
      opts.on('-i T',   'Ignore')   { |t| @ignore_tags << t }
    end.parse!
    @o.v = true if @o.vv
  end

  def parse_in
    Oj.load(ARGF.read).each_pair do |roll_name, images|
      unless (roll = FilmRoll.find(folder: roll_name))
        warn "no roll: #{roll_name}"
        next
      end
      images.each_pair do |jfile|
        jfile[1].each do |ver, meta|
          process_image ImageSt.new(jfile[0], ver, meta, roll.id, roll_name)
        end
      end
    end
  end

  def process_image(img)
    puts "js: #{img.file}:#{img.ver} #{img.meta}" if @o.v
    images = Image
             .select(:id, :write_timestamp, *DT::Geo)
             .where(film_id: img.roll_id, filename: img.file, version: img.ver)
    if images.empty?
      warn "no image in db: #{img.roll_name}/#{img.file} v:#{img.ver}"
    else
      images.each do |i|
        ih = i.to_hash.select { |_, v| v }
        # img: json, ih: database
        if ih[:write_timestamp] >= img.meta['t']
          puts 'local is newer' if @o.vv
          next unless @o.force
        elsif @o.v
          puts 'local is older'
        end
        puts "db: #{ih}" if @o.vv
        process_geo(ih, img.meta['geo']) if img.meta.key?('geo') && !@o.no_geo
        process_meta(ih, img) unless @o.no_meta
        process_tags(ih, img) if @o.add_tag || @o.del_tag
      end
    end
  end

  def process_meta(ihsh, img)
    db_k = {}
    MetaData.where(id: ihsh[:id]).each do |row|
      db_k[[row.id, row.key]] = row.value
    end
    img.meta['k'].each_pair do |k, v|
      db_kk = [ihsh[:id], k.to_i]
      if db_k[db_kk] == v
        puts %(same #{DT::NAMES[k.to_i]} "#{v.truncate(40)}") if @o.vv
        db_k.delete db_kk
        next
      end
      db_k.delete db_kk
      if @o.dry
        res = 'DRY'
        act = 'dry'
      else
        act = 'upd'
        res = MetaData
              .where(id: ihsh[:id], key: k)
              .update(value: v)
        if res.zero?
          act = 'new'
          res = MetaData
                .insert(id: ihsh[:id], key: k, value: v)
        end
      end
      if @o.v
        kn = DT::NAMES[k.to_i]
        puts %(ch #{act} m:#{kn}="#{v}" res:#{res})
      end
    end

    return unless @o.del_meta

    db_k.keys.each do |del|
      d_id, d_k = del
      res = @o.dry ? 'DRY' : MetaData.where(id: d_id, key: d_k).delete
      if @o.v
        kn = DT::NAMES[d_k.to_i]
        puts %(ch del m:#{kn}="#{db_k[del]}" #{d_id} #{d_k} res:#{res})
      end
    end
  end

  def process_tags(ihsh, img)
    tags = (img.meta['tags'] || []).sort
    imgid = ihsh[:id]
    tids = TaggedImage
           .where(imgid: imgid)
           .map(&:tagid)
    db_tags = UsedTag.where(id: tids).order(:name)
                     .select_map(:name)
                     .reject { |t| t.match?(/^darktable\|.+/) }
    puts "t:#{tags} dt:#{db_tags}" if @o.vv
    return if tags == db_tags

    if @o.add_tag
      diff = []
      db_tags_flat = db_tags.map { |dt| dt.split '|' }.flatten.uniq
      (tags - db_tags).each do |nt|
        next if @ignore_tags.include?(nt)

        diff << nt unless db_tags_flat.include?(nt)
      end
      unless diff.empty?
        puts "ch tag add:#{diff}"
        tag_add(imgid, diff) unless @o.dry
      end
    end
    if @o.del_tag
      diff = []
      (db_tags - tags).each do |nt|
        next if @ignore_tags.include?(nt)

        diff << nt
      end
      unless diff.empty?
        puts "ch tag del:#{diff}"
        tag_del(imgid, diff) unless @o.dry
      end
    end
    puts '/tags' if @o.vv
  end

  def tag_add(imgid, tags)
    tags.each do |t|
      u_tag = UsedTag.find(name: t)
      if u_tag
        puts "ch add t:#{t} id:#{u_tag.id}"
        puts TaggedImage.insert(imgid: imgid, tagid: u_tag.id)
      else
        newid = UsedTag.max(:id) + 1
        res_ut = UsedTag.insert(id: newid, name: t)
        res_ti = TaggedImage.insert(imgid: imgid, tagid: newid)
        res_t = Tag.insert(id: newid, name: t)
        puts "ch new t:#{t} id:#{newid}"
        puts "^^ ut:#{res_ut} ti:#{res_ti} t:#{res_t}" if @o.vv
      end
    end
  end

  def tag_del(imgid, tags)
    tags.each do |t|
      id = UsedTag.find(name: t).id
      res = TaggedImage.where(imgid: imgid, tagid: id).delete
      puts "ch del t:#{t} id:#{id} res:#{res}"
      next unless TaggedImage.where(tagid: id).count.zero?

      res_ut = UsedTag.where(id: id).delete
      res_t = Tag.where(id: id).delete
      puts "ch no more used t:#{res_t} ut:#{res_ut}"
    end
  end

  def process_geo(ihsh, geo)
    raise 'no geo data' unless geo

    geo.map!(&:to_f)
    geo.map! { |v| v.round(@o.r_geo) } if @o.r_geo
    nr = { write_timestamp: Time.now.to_i }
    nr[:longitude] = geo[0] if geo[0]
    nr[:latitude]  = geo[1] if geo[1]
    nr[:altitude]  = geo[2] if geo[2]
    og = ihsh.slice(*DT::Geo)
    ng = nr.slice(*DT::Geo)
    og.transform_values! { |v| v.round(@o.r_geo) } if @o.r_geo
    puts "geo old:#{og.values} new:#{ng.values}" if @o.vv
    return if ng == og

    res = @o.dry ? 'DRY' : Image.where(id: ihsh[:id]).update(nr)
    puts "ch geo old:#{og} new:#{ng} res:#{res}"
  end
end

restore = Restore.new
restore.parse_in
