#!/bin/bash

source './meta.conf'

usage() { echo "Usage: $0 [-r <remote hostame>] [-d <remote directory>] [-t]" 1>&2; exit 1; }

cmd='./dt_dump'

while getopts ":r:d:t" o; do
  case "${o}" in
    r)
      r=${OPTARG}
      ;;
    d)
      d=${OPTARG}
      ;;
    t)
      cmd="${cmd} -t"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${r}" ]; then
  r=${default_remote}
fi

if [ -z "${d}" ]; then
  d=$(pwd)
fi

f="z_$(hostname).json"

echo "remote=${r}"
echo "dir=${d}"
echo "file=${f}"
echo "command=${cmd}"

$cmd > $f

#scp -C ${f} ${r}:${d}
rsync -v --compress-level=9 ${f} ${r}:${d}
