#!/bin/bash

remote=$1
dir=$2

source './meta.conf'

usage() { echo "Usage: $0 [-r <remote hostame>] [-d <remote directory>] [-t]" 1>&2; exit 1; }

cmd='./dt_dump'

while getopts ":r:d:t" o; do
  case "${o}" in
    r)
      r=${OPTARG}
      ;;
    d)
      d=${OPTARG}
      ;;
    t)
      cmd="${cmd} -t"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${r}" ]; then
  r=${default_remote}
fi

if [ -z "${d}" ]; then
  d=$(pwd)
fi

echo "remote=${r}"
echo "dir=${d}"
echo "command=${cmd}"

ssh ${r} "eval \"\$(~/.rbenv/bin/rbenv init -)\"; cd ${d} ; bundle exec ${cmd} | gzip" | gunzip > z_${r}.json
